<a href="https://colab.research.google.com/github/2312019/Prodigy_DS_4/blob/main/Prodigy_DS_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Twitter Sentiment Analysis

In [1]:
import pandas as pd

In [1]:
# 🔹 Install required library
!pip install textblob

# 🔹 Import additional libraries
import matplotlib.pyplot as plt
from textblob import TextBlob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.3)

## Load Datasets

In [2]:
training_df = pd.read_csv('/content/twitter_training.csv', header=None, names=['Tweet ID', 'Entity', 'Sentiment', 'Tweet content'])
validation_df = pd.read_csv('/content/twitter_validation.csv', header=None, names=['Tweet ID', 'Entity', 'Sentiment', 'Tweet content'])

### Training Data (First 5 rows)

In [3]:
display(training_df.head())

,Tweet ID,Entity,Sentiment,Tweet content
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

### Validation Data (First 5 rows)

In [4]:
display(validation_df.head())

,Tweet ID,Entity,Sentiment,Tweet content
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...

## Sentiment Analysis with TextBlob

In [2]:
# Select text column (using 'Tweet content' from the training_df)
text_column = 'Tweet content'

# Function to get sentiment
def get_sentiment(text):
    # Ensure text is treated as a string to avoid errors with non-string data types
    analysis = TextBlob(str(text))
    if analysis.sentiment.polarity > 0:
        return "Positive"
    elif analysis.sentiment.polarity < 0:
        return "Negative"
    else:
        return "Neutral"